use `tr` for some "split" functions

diff --git a/splt b/splt
--- a/splt
+++ b/splt
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 
 if [ $# -eq 0 ]; then
-	echo 'Delimiter required'
-	exit 1
+  echo 'Delimiter required'
+  exit 1
 fi
 
 delim="$1"
 shift
 
-if [ ${#delim} -eq 1 -o "$delim" == '\t' ]; then
+if [ ${#delim} -eq 1 ] || [ "$delim" == '\t' ]; then
   if [ $# -gt 0 ]; then
     cat "$@" | tr "$delim" '\n'
   else
